### ISSUE TITLE
Waiting for SSH to become available

### ISSUE THREAD

**Issue by akatukiyou** [ClintWyckoff/packer#1]
I have been trying to make this working for while, all the repos I tested ended up with the same issue including this one.

The build stopped at "waiting for ssh become available" and then times out....

My environment is Packer 1.7.3 + vSphere7.0.2 +  ubuntu20.04

**Comment by ClintWyckoff** [comment]
I recall coming across a similar issue when going through this also. Did you break into the console and validate the server has an IP and VMware tools is running ? VMtools was a pretty reliable point of issue for me when I was building these templates. I do not have access to a VMware environment at the moment to test out further and help diagnose.

**Comment by akatukiyou** [comment]
Thanks :)
